### ISSUE TITLE
WGS84转BD09 几何类型为polygong时报错

### ISSUE THREAD

**Issue by jamesgis** [geocompass/pg-coordtransform#1]
select geoc_wgs84tobd09(geom) from test_table 几何类型为polygong时报错

错误: 函数 geoc_ws84tobd09_line(geometry) 不存在 建议：没有匹配指定名称和参数类型的函数. 您也许需要增加明确的类型转换. 在位置：在赋值的第18行的PL/pgSQL函数geoc_wgs84tobd09_polygon(geometry) 在RETURN的第20行的PL/pgSQL函数geoc_wgs84tobd09(geometry)

**Comment by yikouning** [comment]
非常感谢帮助发现问题，现已解决，回复的有些晚，请见谅。希望能帮助到你

> select geoc_wgs84tobd09(geom) from test_table 几何类型为polygong时报错
> 
> 错误: 函数 geoc_ws84tobd09_line(geometry) 不存在 建议：没有匹配指定名称和参数类型的函数. 您也许需要增加明确的类型转换. 在位置：在赋值的第18行的PL/pgSQL函数geoc_wgs84tobd09_polygon(geometry) 在RETURN的第20行的PL/pgSQL函数geoc_wgs84tobd09(geometry)
