### ISSUE TITLE
关于 2000转 gcj02 后再将 gcj02 转回2000 时,存在的误差是否是无法避免的?

### ISSUE THREAD

**Issue by kasugaharu** [geocompass/pg-coordtransform#10]
POINT(111.43877780268987 27.223905373786593) --2000
SELECT st_astext( geoc_wgs84togcj02(ST_GeomFromText('POINT(111.43877780268987 27.223905373786593)',4490))) --2000转高德
POINT(111.44439660708835 27.220718937598154) --gcj02
SELECT st_astext( geoc_gcj02towgs84(ST_GeomFromText('POINT(111.44439660708835 27.220718937598154)',4490)))--得到的高德反向2000
POINT(111.43878623805693 27.223915830237093)--反向2000 存在米级别的误差

请问这种情况是否正常?

**Comment by yikouning** [comment]
因为是用公式计算的，多少会有一些误差的，一两米是正常的
