### ISSUE TITLE
可否对Z坐标进行保留?

### ISSUE THREAD

**Issue by kasugaharu** [geocompass/pg-coordtransform#11]
由于坐标点位存在Z坐标,进行转换后能否对Z坐标进行保留,
e.g.
SELECT st_z( geoc_wgs84togcj02(ST_Transform ( ST_GeomFromText ( 'POINT Z(543464.504 3012516.33 232.408)', 4546 ), 4490 )));
SELECT st_z(geoc_gcj02towgs84(ST_Transform ( ST_GeomFromText ( 'POINT Z(543464.504 3012516.33 232.408)', 4546 ), 4490 )));
返回Z 都为NULL

**Comment by MrSmallLiu** [comment]
可以保留，不知道你是否愿意参与这项功能的开发工作
