### ISSUE TITLE
是否增加一下国家主推的CGCS2000坐标的转换

### ISSUE THREAD

**Issue by sulumaenjun** [geocompass/pg-coordtransform#2]

**Comment by MrSmallLiu** [comment]
收到您的建议，我们会将您的建议列入到我们的计划中，完成后会立即上线。预计完成时间为下周，您可以关注我们的更新，同时也感谢您对pg-coordtransform的使用以及建议。 @sulumaenjun

**Comment by MrSmallLiu** [comment]
现已增加CGCS2000坐标系的转换，您可以更新使用，有任何问题可以提Issues，我们会第一时间解决。感谢您的使用。
