### ISSUE TITLE
geoc_wgs84togcj02_point函数是否重复定义了

### ISSUE THREAD

**Issue by www-uu** [geocompass/pg-coordtransform#4]
![图片](https://user-images.githubusercontent.com/7844108/94524589-638bf080-0265-11eb-9cab-732ec0bb74b2.png)

![图片](https://user-images.githubusercontent.com/7844108/94524630-743c6680-0265-11eb-869e-98f65e37a8f3.png)

![图片](https://user-images.githubusercontent.com/7844108/94524488-3fc8aa80-0265-11eb-9c39-26b4dd74cc1b.png)

**Comment by MrSmallLiu** [comment]
感谢您提出的问题，其中有一个文件重复了，现已提交
