### ISSUE TITLE
w84转到cjcs2000，这样是否可行

### ISSUE THREAD

**Issue by whbq** [geocompass/pg-coordtransform#5]
geoc_gcj02tocgcs2000(st_setsrid(geoc_wgs84togcj02(st_setsrid(geom,4326)),'4490')))

**Comment by whbq** [comment]
> geoc_gcj02tocgcs2000(st_setsrid(geoc_wgs84togcj02(st_setsrid(geom,4326)),'4490')))

**Comment by MrSmallLiu** [comment]
wgs84和cgcs2000如果精度要求不是很高，例如到几厘米要求，可以近似的认为两者使用一个就行
