### ISSUE TITLE
关于BD09转WGS84函数使用的问题

### ISSUE THREAD

**Issue by Davwei** [geocompass/pg-coordtransform#8]
我有BD09的坐标经纬度，需要通过这个函数转换，那么用一个geom存储bd09经纬度调用geoc_bd09towgs84_point(gemo)是一个好主意，但是我在运行的时候报错显示经纬度值不能包含小数点，请问这个函数正确的使用方法是什么呢

**Comment by yikouning** [comment]
需要先把经纬度转成geometry类型数据，可以使用postgis相关的函数，比如 geom=ST_GeomFromText('POINT(108.658463 34.1437)', 4326)
