### ISSUE TITLE
你好，请教一个问题，关于gcj02转wgs84的

### ISSUE THREAD

**Issue by qzwzqty** [geocompass/pg-coordtransform#9]
我现在只有gcj02的坐标，想转换为wgs84之后存入数据库，我看geoc_gcj02towgs84方法里面做了限制，只能传入4490和4326的坐标。想请问下为什么这样设计？按照这个方法的设计，意思是我存入数据的时候，坐标系就应该选择4490或者4326，但是数据还是存gcj02的？谢了

**Comment by MrSmallLiu** [comment]
因为srid没有gcj02
